config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[index new create]

  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, AvatarUploader
  validates :name, :email, :age, presence: true  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users or /users.json
  def index
    @users = User.all.order("created_at DESC")
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path 
    else
      render :new 
    end
  end
end

private

# Only allow a list of trusted parameters through.
def user_params
  params.require(:user).permit(:name, :age, :email, :image)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCarrierwave</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="column">
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <div class="field">
        <div class="control">
          <%= f.input :name, required: true, input_html: { class: "input" }, label_html: { class: "label" }, wrapper: false %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.input :age, required: true, input_html: { class: "input" }, label_html: { class: "label" }, wrapper: false %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.input :email, required: true, input_html: { class: "input" }, label_html: { class: "label" }, wrapper: false %>
        </div>
      </div>
      <div class="field">
        <div class="control">
          <label class="label">Добавить фото</label>
          <div class="file">
            <label class="file-label">
              <%= f.input :image, as: :file, input_html: { class:"file-input" }, label: false, wrapper: false %>
              <span class="file-cta">
                <span class="file-icon"><i class="fa fa-upload"></i></span>
                <span class="file-label">Выбрать файл</span>
              </span>
            </label>
          </div>   
        </div>
      </div>
      <div class="field">
        <div class="control">
          <%= f.submit 'Создать', class: 'button is-primary' %>
        </div>
      </div>
    </div>
  <% end %>   
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<section class="section">
  <div class="container mt-5">
    <h1 class="title is-3">Cписок пользователей</h1>
    <%= link_to "Добавить пользователя", new_user_path, class: "button is-primary mb-5" %>  
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-4">
          <div class="box">
            <div class="media">
              <figure class="media-left">
                <p class="image">
                  <%= link_to image_tag(user.image.thumb.url, alt: 'Image') if user.image? %>
                </p>
              </figure>
              <div class="media-content">
                <p>
                  <strong><%= user.name %></strong>
                  <small> <%= user.email %> </small>
                  </br>
                  <p>
                    Lorem voluptas maiores excepturi molestiae quam quae eius doloribus asperiores Blanditiis accusantium repellendus dolor aliquid unde.
                  </p>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section> 

app/views/users/new.html.erb
<div class="container mt-5">
 <h1 class="title is-3">Новый пользователь</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Вернуться", users_path %>
</div> 
</div>